<a href="https://colab.research.google.com/github/Paulina9555/Test/blob/master/statystyka_i_prawdopodobienstwo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Zadanie 1

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
numbers = np.arange(100)

In [ ]:
numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
numbers = np.array([x for x in range (1000,1,-1) if x % 11==0])

In [ ]:
print(numbers)

[990 979 968 957 946 935 924 913 902 891 880 869 858 847 836 825 814 803
 792 781 770 759 748 737 726 715 704 693 682 671 660 649 638 627 616 605
 594 583 572 561 550 539 528 517 506 495 484 473 462 451 440 429 418 407
 396 385 374 363 352 341 330 319 308 297 286 275 264 253 242 231 220 209
 198 187 176 165 154 143 132 121 110  99  88  77  66  55  44  33  22  11]


In [ ]:
numbers = np.linspace(-5,5,70)

In [ ]:
print(numbers)

[-5.         -4.85507246 -4.71014493 -4.56521739 -4.42028986 -4.27536232
 -4.13043478 -3.98550725 -3.84057971 -3.69565217 -3.55072464 -3.4057971
 -3.26086957 -3.11594203 -2.97101449 -2.82608696 -2.68115942 -2.53623188
 -2.39130435 -2.24637681 -2.10144928 -1.95652174 -1.8115942  -1.66666667
 -1.52173913 -1.37681159 -1.23188406 -1.08695652 -0.94202899 -0.79710145
 -0.65217391 -0.50724638 -0.36231884 -0.2173913  -0.07246377  0.07246377
  0.2173913   0.36231884  0.50724638  0.65217391  0.79710145  0.94202899
  1.08695652  1.23188406  1.37681159  1.52173913  1.66666667  1.8115942
  1.95652174  2.10144928  2.24637681  2.39130435  2.53623188  2.68115942
  2.82608696  2.97101449  3.11594203  3.26086957  3.4057971   3.55072464
  3.69565217  3.84057971  3.98550725  4.13043478  4.27536232  4.42028986
  4.56521739  4.71014493  4.85507246  5.        ]


#Zadanie 2

In [ ]:
A = np.array([[1,4,7],
             [2,5,8],
             [3,6,9]])

B = np.array([[3,2,3],
             [4,3,1],
             [7,3,1]])

print(A)
print(B)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[3 2 3]
 [4 3 1]
 [7 3 1]]


In [ ]:
A.shape

(3, 3)

In [ ]:
C = np.add(A,B)
C

array([[ 4,  6, 10],
       [ 6,  8,  9],
       [10,  9, 10]])

In [ ]:
C.shape

(3, 3)

In [ ]:
D =np.subtract(A,B)
D

array([[-2,  2,  4],
       [-2,  2,  7],
       [-4,  3,  8]])

In [ ]:
D.shape

(3, 3)

In [ ]:
print(A.T)
print(B.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 4 7]
 [2 3 3]
 [3 1 1]]


In [ ]:
A.T.shape

(3, 3)

In [ ]:
B.T.shape

(3, 3)

In [ ]:
E = np.multiply(A,B)
E

array([[ 3,  8, 21],
       [ 8, 15,  8],
       [21, 18,  9]])

In [ ]:
E.shape

(3, 3)

In [ ]:
F =np.divide(A,B)
F

array([[0.33333333, 2.        , 2.33333333],
       [0.5       , 1.66666667, 8.        ],
       [0.42857143, 2.        , 9.        ]])

In [ ]:
F.shape

(3, 3)

#Zadanie 3

In [ ]:
X = np.arange(0, np.pi, 0.1)
sinus = np.sin(X)
cosinus = np.cos(X)

In [ ]:
sinus

array([0.        , 0.09983342, 0.19866933, 0.29552021, 0.38941834,
       0.47942554, 0.56464247, 0.64421769, 0.71735609, 0.78332691,
       0.84147098, 0.89120736, 0.93203909, 0.96355819, 0.98544973,
       0.99749499, 0.9995736 , 0.99166481, 0.97384763, 0.94630009,
       0.90929743, 0.86320937, 0.8084964 , 0.74570521, 0.67546318,
       0.59847214, 0.51550137, 0.42737988, 0.33498815, 0.23924933,
       0.14112001, 0.04158066])

In [ ]:
cosinus

array([ 1.        ,  0.99500417,  0.98006658,  0.95533649,  0.92106099,
        0.87758256,  0.82533561,  0.76484219,  0.69670671,  0.62160997,
        0.54030231,  0.45359612,  0.36235775,  0.26749883,  0.16996714,
        0.0707372 , -0.02919952, -0.12884449, -0.22720209, -0.32328957,
       -0.41614684, -0.5048461 , -0.58850112, -0.66627602, -0.73739372,
       -0.80114362, -0.85688875, -0.90407214, -0.94222234, -0.97095817,
       -0.9899925 , -0.99913515])

In [ ]:
A = np.arange(-100,100, step=2)
A

array([-100,  -98,  -96,  -94,  -92,  -90,  -88,  -86,  -84,  -82,  -80,
        -78,  -76,  -74,  -72,  -70,  -68,  -66,  -64,  -62,  -60,  -58,
        -56,  -54,  -52,  -50,  -48,  -46,  -44,  -42,  -40,  -38,  -36,
        -34,  -32,  -30,  -28,  -26,  -24,  -22,  -20,  -18,  -16,  -14,
        -12,  -10,   -8,   -6,   -4,   -2,    0,    2,    4,    6,    8,
         10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98])

In [ ]:
B = np.arange(0, 21, step=1)
C = np.array(2**B)
C

array([      1,       2,       4,       8,      16,      32,      64,
           128,     256,     512,    1024,    2048,    4096,    8192,
         16384,   32768,   65536,  131072,  262144,  524288, 1048576])

In [ ]:
D = np.array(3**B)
D

array([         1,          3,          9,         27,         81,
              243,        729,       2187,       6561,      19683,
            59049,     177147,     531441,    1594323,    4782969,
         14348907,   43046721,  129140163,  387420489, 1162261467,
       3486784401])

In [ ]:
E = C + D[::-1]
E

array([3486784402, 1162261469,  387420493,  129140171,   43046737,
         14348939,    4783033,    1594451,     531697,     177659,
            60073,      21731,      10657,      10379,      17113,
            33011,      65617,     131099,     262153,     524291,
          1048577])

#Zadanie 4

In [ ]:
A = np.arange(1,102)
A

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101])

In [ ]:
result = sum(1/A)
result

5.1972785077386305

In [ ]:
result = sum(1/np.sqrt(A))
result

18.689107543805147

In [ ]:
result = sum((1+1/A)**A)
result

268.74089438451426

#Zadanie 5

In [ ]:
A = np.arange(0,49, step=1)
B = A.reshape(7,7)
B

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [ ]:
print(B[[3], [4]])

[25]


In [ ]:
B[[5], [2]]=np.pi
B

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36,  3, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [ ]:
C = B[:3, 1:-1]
C

array([[ 1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12],
       [15, 16, 17, 18, 19]])

In [ ]:
D = B[:,:3]
D

array([[ 0,  1,  2],
       [ 7,  8,  9],
       [14, 15, 16],
       [21, 22, 23],
       [28, 29, 30],
       [35, 36,  3],
       [42, 43, 44]])

In [ ]:
E = B[-4:,:]
E

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36,  3, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

#Zadanie 6

In [ ]:
A = np.arange(0,36, step=1)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
B = A.reshape(2,18)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35]])

In [ ]:
C = A.reshape(3,12)
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
D = A.reshape(4,9)
D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

#Zadanie 7

In [ ]:
A = np.ones(shape=(100,100))
B = np.expand_dims(np.arange(1,101),1)

C = A * B
C

array([[  1.,   1.,   1., ...,   1.,   1.,   1.],
       [  2.,   2.,   2., ...,   2.,   2.,   2.],
       [  3.,   3.,   3., ...,   3.,   3.,   3.],
       ...,
       [ 98.,  98.,  98., ...,  98.,  98.,  98.],
       [ 99.,  99.,  99., ...,  99.,  99.,  99.],
       [100., 100., 100., ..., 100., 100., 100.]])

#Zadanie 8

In [ ]:
A = np.arange(0,10, step = 1)
A.reshape(2,5)
B = np.arange(10,20, step = 1)
B.reshape(2,5)
C = np.arange(20,30, step = 1)
C.reshape(2,5)

D = np.stack((A,B,C), axis = 0)
D1 = np.stack((A,B,C), axis = 1)
#D2 = np.stack((A,B,C), axis = 2)

In [ ]:
print(D[0,0])
print(D[1,1])
print(D1[0,0])
print(D1[1,1])

0
11
0
11


In [ ]:
print(D.shape)
print(D1.shape)

(3, 10)
(10, 3)


In [ ]:
print(np.sum(D))
print(np.sum(D1))

435
435


#Statystyka opisowa, zadanie 1

In [ ]:
    def converter(x):
        try:
            return float(x.decode("utf-8").replace('"', ''))
        except ValueError:
            print('non-numerical input')

    data = np.to_csv(
        "MDR_RR_TB_burden_estimates_2022-01-03.csv",
        delimiter=',',
        usecols=(3,),
        converters = {3: converter},
        skiprows=1,
        unpack=True
    )
    data = data[np.logical_not(np.isnan(data))]


AttributeError: ignored

In [ ]:
 def print_basic_stats(data):
        print("Max:", np.max(data))
        print("Min:", np.min(data))
        print("Mean:", np.mean(data))
        print("Median:", np.median(data))
        print("Standard deviation:", np.std(data))
        print("Variance:", np.var(data))

#Statystyka opisowa, zadanie 2

In [ ]:
wzrost = pd.read_csv('Wzrost.csv')

In [ ]:
print_basic_stats(wzrost)

Max: 156      NaN
158      NaN
167      NaN
188      NaN
197      NaN
167.1    NaN
197.1    NaN
178      NaN
186      NaN
157      NaN
198      NaN
199      NaN
178.1    NaN
168      NaN
156.1    NaN
151      NaN
167.2    NaN
167.3    NaN
dtype: object
Min: 156      NaN
158      NaN
167      NaN
188      NaN
197      NaN
167.1    NaN
197.1    NaN
178      NaN
186      NaN
157      NaN
198      NaN
199      NaN
178.1    NaN
168      NaN
156.1    NaN
151      NaN
167.2    NaN
167.3    NaN
dtype: object
Mean: 156      NaN
158      NaN
167      NaN
188      NaN
197      NaN
167.1    NaN
197.1    NaN
178      NaN
186      NaN
157      NaN
198      NaN
199      NaN
178.1    NaN
168      NaN
156.1    NaN
151      NaN
167.2    NaN
167.3    NaN
dtype: object
Median: nan
Standard deviation: 156      NaN
158      NaN
167      NaN
188      NaN
197      NaN
167.1    NaN
197.1    NaN
178      NaN
186      NaN
157      NaN
198      NaN
199      NaN
178.1    NaN
168      NaN
156.1    NaN
151      NaN


/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.max(axis=None) will return a scalar max over the entire DataFrame. To retain the old behavior, use 'frame.max(axis=0)' or just 'frame.max()'
  return reduction(axis=axis, out=out, **passkwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.min(axis=None) will return a scalar min over the entire DataFrame. To retain the old behavior, use 'frame.min(axis=0)' or just 'frame.min()'
  return reduction(axis=axis, out=out, **passkwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumer

In [ ]:
  import scipy.stats as scs

# Rozkłady prawdopodobieństwa zmiennej losowej, zadanie 1

In [ ]:
    import scipy.stats as scs
    p = 0.3
    data = scs.bernoulli.rvs(p, size=1000)
    mean, var, skew, kurt = scs.bernoulli.stats(p, moments ='mvsk')
    print(mean, var, skew, kurt)

0.3 0.21 0.8728715609439694 -1.2380952380952381


#Rozkłady prawdopodobieństwa zmiennej losowej, zadanie 2

In [ ]:
    #Bernoulli
    import scipy.stats as scs
    p = 0.3
    data = scs.bernoulli.rvs(p, size=100)
    mean, var, skew, kurt = scs.bernoulli.stats(p, moments ='mvsk')
    print(mean, var, skew, kurt)

    #Binomial
    n, p = 5, 0.4
    date = scs.binom.rvs(n, p, size=100)
    mean, var, skew, kurt = scs.binom.stats(n, p, moments='mvsk')
    print(mean, var, skew, kurt)

    #Poisson
    mu = 0.6
    date = scs.poisson.rvs(mu,loc=0, size=100, random_state=None)
    mean, var, skew, kurt = scs.poisson.stats(mu, moments='mvsk')
    print(mean, var, skew, kurt)



0.3 0.21 0.8728715609439694 -1.2380952380952381
2.0 1.2 0.18257418583505533 -0.3666666666666668
0.6 0.6 1.2909944487358056 1.6666666666666667


#Testy statystyczne, zadanie 1

In [ ]:
import scipy.stats as scs
alpha = 0.01

data = scs.norm.rvs(loc=2, scale=0.3, size=200)
resultsNorm = scs.ttest_1samp(data, 2.5)
if resultsNorm.pvalue < alpha:
        print("Hipothesis rejected!")
else:
        print("Hipothesis accepted")


Hipothesis rejected!


#Testy statystyczne, zadanie 2

In [ ]:
alpha = 0.05
    drinks_data = pd.read_csv("napoje.csv", sep=';', na_values='.')
    drink_types = ['lech', 'cola', 'regional']
    mean_values = [60500, 222000, 43500]
    for k in range(0, len(mean_values)):
        result = sps.ttest_1samp(drinks_data[drink_types[k]], mean_values[k])
        print('Mean %s: %.2f. Tested value: %.2f' % (drink_types[k], drinks_data[drink_types[k]].mean(),mean_values[k]))

        if result.pvalue < alpha:
            print("Hipothesis rejected!")
        else:
            print("Hipothesis accepted")

IndentationError: ignored